<a href="https://colab.research.google.com/gist/gabvalen/dc66b8c108d70db85e68af64e8387fab/semana-2-exerc-cio-de-apoio-introdu-o-a-ciencia-de-dados-com350-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###1 - Carregue as bibliotecas NumPy e Pandas

In [ ]:
import numpy as np
import pandas as pd


###2 - Crie um NDArray com os seguintes valores [1, 2.5, 7, -78, -0.9, 130, 25]

In [ ]:
import numpy as np

# Criando o array NumPy com os valores fornecidos
array = np.array([1, 2.5, 7, -78, -0.9, 130, 25])

print("NDArray criado:")
print(array)


NDArray criado:
[  1.    2.5   7.  -78.   -0.9 130.   25. ]


###3 - Crie um NDArray com os valores de 0 a 10

In [ ]:
import numpy as np

# Criando o array NumPy com os valores de 0 a 10
array = np.arange(11)

print("NDArray criado:")
print(array)


NDArray criado:
[ 0  1  2  3  4  5  6  7  8  9 10]


##Disciplina - Introdução a Ciência de Dados - Univesp
##Exercícios de Apoio da Semana 2

###4 – Crie um NDArray de dimensão 2x5 com valores 1

In [ ]:
import numpy as np

# Criando o array NumPy de dimensão 2x5 com valores 1
array = np.ones((2, 5))

print("NDArray criado:")
print(array)


NDArray criado:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


###5 – Crie um NDArray com valores de 1 a 100, com intervalos de 3 em 3.

In [ ]:
import numpy as np

# Criando o array NumPy com valores de 1 a 100, com intervalos de 3 em 3
array = np.arange(1, 101, 3)

print("NDArray criado:")
print(array)


NDArray criado:
[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


###6 – Mostre as raízes quadradas dos valores do NDArray criado no exercícios 5.

In [ ]:
import numpy as np

# Criando o array NumPy com valores de 1 a 100, com intervalos de 3 em 3
array = np.arange(1, 101, 3)

# Calculando as raízes quadradas dos valores do array
raizes_quadradas = np.sqrt(array)

print("Raízes quadradas dos valores do NDArray:")
print(raizes_quadradas)


Raízes quadradas dos valores do NDArray:
[ 1.          2.          2.64575131  3.16227766  3.60555128  4.
  4.35889894  4.69041576  5.          5.29150262  5.56776436  5.83095189
  6.08276253  6.32455532  6.55743852  6.78232998  7.          7.21110255
  7.41619849  7.61577311  7.81024968  8.          8.18535277  8.36660027
  8.54400375  8.71779789  8.88819442  9.05538514  9.21954446  9.38083152
  9.53939201  9.69535971  9.8488578  10.        ]


###7 – Altere a décima posição do NDArray criado no exercício 5 com o dobro do seu valor.

In [ ]:
import numpy as np

# Criando o array NumPy com valores de 1 a 100, com intervalos de 3 em 3
array = np.arange(1, 101, 3)

# Exibindo o array antes da alteração
print("NDArray antes da alteração:")
print(array)



NDArray antes da alteração:
[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


###8 – Execute o comando para criar um Dataframe com os dados disponíveis no notebook.

In [ ]:
dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

###9 – Execute um comando que seja possível identificar qual a média da quantidade de funcionários que as empresas listadas tem. Informe também a soma dos funcionários que as empresas tem.


In [ ]:
import numpy as np

# Lista de quantidade de funcionários das empresas
quantidade_funcionarios = [100, 50, 200, 150, 80]

# Criando um array NumPy com os valores da lista
funcionarios_array = np.array(quantidade_funcionarios)

# Calculando a média da quantidade de funcionários
media_funcionarios = np.mean(funcionarios_array)

# Calculando a soma total dos funcionários
soma_funcionarios = np.sum(funcionarios_array)

# Exibindo a média e a soma
print("Média da quantidade de funcionários:", media_funcionarios)
print("Soma total dos funcionários:", soma_funcionarios)


Média da quantidade de funcionários: 116.0
Soma total dos funcionários: 580


###10 – Mostre as primeiras 3 linhas do dataframe.

In [ ]:
import pandas as pd

# Criar um dicionário com os dados
dados = {
    'Empresa': ['Microsoft', 'Google', 'Univesp', 'NVData'],
    'Quantidade de funcionários': [181, 98, 50, 125]
}

# Criar o dataframe a partir do dicionário
df = pd.DataFrame(dados)

# Mostrar as primeiras 3 linhas do dataframe
primeiras_tres_linhas = df.head(3)
print(primeiras_tres_linhas)


     Empresa  Quantidade de funcionários
0  Microsoft                         181
1     Google                          98
2    Univesp                          50


###11 – Mostre as últimas 3 linhas do dataframe.

In [ ]:
import pandas as pd

# Criar um dicionário com os dados
dados = {
    'Empresa': ['Microsoft', 'Google', 'Univesp', 'NVData'],
    'Quantidade de funcionários': [181, 98, 50, 125]
}

# Criar o dataframe a partir do dicionário
df = pd.DataFrame(dados)

# Mostrar as últimas 3 linhas do dataframe
ultimas_tres_linhas = df.tail(3)
print(ultimas_tres_linhas)


   Empresa  Quantidade de funcionários
1   Google                          98
2  Univesp                          50
3   NVData                         125


###12 – Liste apenas as linhas em que as empresas foram criadas nos últimos 10 anos. Informe a quantidade de registros.

In [ ]:
import pandas as pd

# Criar um dicionário com os dados (incluindo a data de criação das empresas)
dados = {
    'Empresa': ['Microsoft', 'Google', 'Univesp', 'NVData'],
    'Quantidade de funcionários': [181, 98, 50, 125],
    'Ano de Criação': [1975, 1998, 2012, 2015]  # Exemplo de anos de criação das empresas
}

# Criar o dataframe a partir do dicionário
df = pd.DataFrame(dados)

# Calcular o ano atual
ano_atual = 2024

# Filtrar as linhas onde as empresas foram criadas nos últimos 10 anos
empresas_ultimos_10_anos = df[df['Ano de Criação'] >= ano_atual - 10]

# Imprimir as empresas criadas nos últimos 10 anos
print(empresas_ultimos_10_anos)

# Informar a quantidade de registros
quantidade_registros = len(empresas_ultimos_10_anos)
print("Quantidade de registros:", quantidade_registros)


  Empresa  Quantidade de funcionários  Ano de Criação
3  NVData                         125            2015
Quantidade de registros: 1


###13 – Vamos imaginar que em todas as empresas exista 1 chefe para cada 23 funcionários. Crie uma coluna que mostre a quantidade de chefes que cada empresa teria e depois informe quantos chefes teríamos ao todo. (os valores não precisam ser números inteiros, é apenas uma estimativa).


In [ ]:
import pandas as pd

# Criar um dicionário com os dados (incluindo a quantidade de funcionários)
dados = {
    'Empresa': ['Microsoft', 'Google', 'Univesp', 'NVData'],
    'Quantidade de funcionários': [181, 98, 50, 125],
    'Ano de Criação': [1975, 1998, 2012, 2015]  # Exemplo de anos de criação das empresas
}

# Criar o dataframe a partir do dicionário
df = pd.DataFrame(dados)

# Calcular o número estimado de chefes para cada empresa
df['Quantidade de chefes'] = df['Quantidade de funcionários'] / 23

# Arredondar para cima o número estimado de chefes, já que não pode haver frações de chefes
df['Quantidade de chefes'] = df['Quantidade de chefes'].apply(lambda x: round(x))

# Somar o número estimado de chefes em todas as empresas
total_chefes = df['Quantidade de chefes'].sum()

# Imprimir o dataframe com a nova coluna
print(df)

# Imprimir o total de chefes
print("Total de chefes:", total_chefes)


     Empresa  Quantidade de funcionários  Ano de Criação  Quantidade de chefes
0  Microsoft                         181            1975                     8
1     Google                          98            1998                     4
2    Univesp                          50            2012                     2
3     NVData                         125            2015                     5
Total de chefes: 19
